export const players = {
  SRH: {
    teamPlayers: [
      { name: "Aiden Markram", photo: "/srh.png" },
      { name: "Abdul Samad", photo: "/srh.png" },
      { name: "Rahul Tripathi", photo: "/srh.png" },
      { name: "Glenn Phillips", photo: "/srh.png" },
      { name: "Heinrich Klaasen", photo: "/srh.png" },
      { name: "Mayank Agarwal", photo: "/srh.png" },
      { name: "Anmolpreet Singh", photo: "/srh.png" },
      { name: "Upendra Yadav", photo: "/srh.png" },
      { name: "Nitish Reddy", photo: "/srh.png" },
      { name: "Shahbaz Ahmed (Traded from RCB)", photo: "/srh.png" },
      { name: "Abhishek Sharma", photo: "/srh.png" },
      { name: "Marco Jansen", photo: "/srh.png" },
      { name: "Washington Sundar", photo: "/srh.png" },
      { name: "Sanvir Singh", photo: "/srh.png" },
      { name: "Bhuvneshwar Kumar", photo: "/srh.png" },
      { name: "Mayank Markande", photo: "/srh.png" },
      { name: "Umran Malik", photo: "/srh.png" },
      { name: "T Natarajan", photo: "/srh.png" },
      { name: "Fazahaq Farooqi", photo: "/srh.png" },
      { name: "Travis Head", photo: "/srh.png" },
      { name: "Wanindu Hasaranga", photo: "/srh.png" },
      { name: "Pat Cummins", photo: "/srh.png" },
      { name: "Jaydev Unadkat", photo: "/srh.png" },
      { name: "Akash Maharaj Singh", photo: "/srh.png" },
      { name: "Jhathavedh Subramanyam", photo: "/srh.png" },
    ],
    logo: "",
  },
  MI: {
    teamPlayers: [
      { name: "Hardik Pandya (Traded from GT)", photo: "/mi.jpeg" },
      { name: "Rohit Sharma", photo: "/mi.jpeg" },
      { name: "Dewald Brevis", photo: "/mi.jpeg" },
      { name: "Suryakumar Yadav", photo: "/mi.jpeg" },
      { name: "Ishan Kishan", photo: "/mi.jpeg" },
      { name: "Tilak Varma", photo: "/mi.jpeg" },
      { name: "Tim David", photo: "/mi.jpeg" },
      { name: "Vishnu Vinod", photo: "/mi.jpeg" },
      { name: "Arjun Tendulkar", photo: "/mi.jpeg" },
      { name: "Shams Mulani", photo: "/mi.jpeg" },
      { name: "Nehal Wadhera", photo: "/mi.jpeg" },
      { name: "Jasprit Bumrah", photo: "/mi.jpeg" },
      { name: "Kumar Kartikeya", photo: "/mi.jpeg" },
      { name: "Piyush Chawla", photo: "/mi.jpeg" },
      { name: "Akash Madhwal", photo: "/mi.jpeg" },
      { name: "Jason Behrendorff", photo: "/mi.jpeg" },
      { name: "Romario Shepherd (Traded from LSG)", photo: "/mi.jpeg" },
      { name: "Gerald Coetzee", photo: "/mi.jpeg" },
      { name: "Dilshan Madhushanka", photo: "/mi.jpeg" },
      { name: "Shreyas Gopal", photo: "/mi.jpeg" },
      { name: "Nuwan Thushara", photo: "/mi.jpeg" },
      { name: "Namandhir Singh", photo: "/mi.jpeg" },
      { name: "Anshul Kamboj", photo: "/mi.jpeg" },
      { name: "Mohammad Nabi", photo: "/mi.jpeg" },
    ],
    logo: "",
  },
  DC: {
    teamPlayers: [
      {
        name: "Rishabh Pant",
        photo:
          "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/18.png",
      },
      { name: "Pravin Dubey", photo: "/dc.png" },
      {
        name: "David Warner",
        photo:
          "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/214.png",
      },
      { name: "Vicky Ostwal", photo: "/dc.png" },
      {
        name: "Prithvi Shaw",
        photo:
          "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/51.png",
      },
      {
        name: "Anrich Nortje",
        photo:
          "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/142.png",
      },
      {
        name: "Abishek Porel",
        photo:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQh8XJjhf4cD3LCnC6FX_twmYFBfX2D7pX9OQ&s",
      },
      { name: "Kuldeep Yadav", photo: "/dc.png" },
      { name: "Axar Patel", photo: "/dc.png" },
      { name: "Lungi Ngidi", photo: "/dc.png" },
      { name: "Lalit Yadav", photo: "/dc.png" },
      { name: "Khaleel Ahmed", photo: "/dc.png" },
      { name: "Mitchell Marsh", photo: "/dc.png" },
      { name: "Ishant Sharma", photo: "/dc.png" },
      { name: "Yash Dhull", photo: "/dc.png" },
      { name: "Mukesh Kumar", photo: "/dc.png" },
      { name: "Harry Brook", photo: "/dc.png" },
      { name: "Tristan Stubbs", photo: "/dc.png" },
      { name: "Ricky Bhui", photo: "/dc.png" },
      { name: "Kumar Kushagra", photo: "/dc.png" },
      { name: "Rasikh Dar", photo: "/dc.png" },
      { name: "Jhye Richardson", photo: "/dc.png" },
      { name: "Sumit Kumar", photo: "/dc.png" },
      { name: "Shai Hope", photo: "/dc.png" },
      { name: "Swastik Chhikara", photo: "/dc.png" },
    ],
    logo: "",
  },
  CSK: {
    teamPlayers: [
      { name: "MS Dhoni", photo: "/csk.png" },
      { name: "Ravindra Jadeja", photo: "/csk.png" },
      { name: "Ruturaj Gaikwad", photo: "/csk.png" },
      { name: "Ajinkya Rahane", photo: "/csk.png" },
      { name: "Deepak Chahar", photo: "/csk.png" },
      { name: "Devon Conway", photo: "/csk.png" },
      { name: "Moeen Ali", photo: "/csk.png" },
      { name: "Shivam Dube", photo: "/csk.png" },
      { name: "Maheesh Theekshana", photo: "/csk.png" },
      { name: "Mitchell Santner", photo: "/csk.png" },
      { name: "Matheesha Pathirana", photo: "/csk.png" },
      { name: "Tushar Deshpande", photo: "/csk.png" },
      { name: "Rajvardhan Hangargekar", photo: "/csk.png" },
      { name: "Mukesh Choudhary", photo: "./csk.png" },
      { name: "Simarjeet Singh", photo: "./csk.png" },
      { name: "Shaik Rasheed", photo: "./csk.png" },
      { name: "Nishant Sindhu", photo: "./csk.png" },
      { name: "Prashant Solanki", photo: "./csk.png" },
      { name: "Ajay Mandal", photo: "./csk.png" },
      { name: "Rachin Ravindra", photo: "./csk.png" },
      { name: "Shardul Thakur", photo: "./csk.png" },
      { name: "Daryl Mitchell", photo: "./csk.png" },
      { name: "Sameer Rizvi", photo: "./csk.png" },
      { name: "Avanish Rao Aravelly", photo: "./csk.png" },
      { name: "Mustafizur Rahman", photo: "./csk.png" },
    ],
    logo: "",
  },
  GT: {
    teamPlayers: [
      { name: "Shubman Gill", photo: "/gt.png" },
      { name: "Matthew Wade", photo: "/gt.png" },
      { name: "Wriddhiman Saha", photo: "/gt.png" },
      { name: "Kane Williamson", photo: "/gt.png" },
      { name: "David Miller", photo: "/gt.png" },
      { name: "Abhinav Manohar", photo: "/gt.png" },
      { name: "Sai Sudharsan", photo: "/gt.png" },
      { name: "Darshan Nalkande", photo: "/gt.png" },
      { name: "Vijay Shankar", photo: "/gt.png" },
      { name: "Jayant Yadav", photo: "/gt.png" },
      { name: "Rahul Tewatia", photo: "/gt.png" },
      { name: "Mohammed Shami", photo: "/gt.png" },
      { name: "Noor Ahmad", photo: "/gt.png" },
      { name: "R Sai Kishore", photo: "/gt.png" },
      { name: "Rashid Khan", photo: "/gt.png" },
      { name: "Josh Little", photo: "/gt.png" },
      { name: "Mohit Sharma", photo: "/gt.png" },
      { name: "Azmatullah Omarzai", photo: "/gt.png" },
      { name: "Umesh Yadav", photo: "/gt.png" },
      { name: "Manav Suthar", photo: "/gt.png" },
      { name: "Shahrukh Khan", photo: "/gt.png" },
      { name: "Sushant Mishra", photo: "/gt.png" },
      { name: "Kartik Tyagi", photo: "/gt.png" },
      { name: "Spencer Johnson", photo: "/gt.png" },
      { name: "Robin Minz", photo: "/gt.png" },
    ],
    logo: "",
  },
  KKR: {
    teamPlayers: [
      { name: "Shreyas Iyer", photo: "/kkr.png" },
      { name: "Nitish Rana", photo: "/kkr.png" },
      { name: "Rinku Singh", photo: "/kkr.png" },
      { name: "Rahmanullah Gurbaz", photo: "/kkr.png" },
      { name: "Sunil Narine", photo: "/kkr.png" },
      { name: "Jason Roy", photo: "/kkr.png" },
      { name: "Suyash Sharma", photo: "/kkr.png" },
      { name: "Anukul Roy", photo: "/kkr.png" },
      { name: "Andre Russell", photo: "/kkr.png" },
      { name: "Venkatesh Iyer", photo: "/kkr.png" },
      { name: "Harshit Rana", photo: "/kkr.png" },
      { name: "Vaibhav Arora", photo: "/kkr.png" },
      { name: "Varun Chakravarthy", photo: "/kkr.png" },
      { name: "KS Bharat", photo: "/kkr.png" },
      { name: "Chetan Sakariya", photo: "/kkr.png" },
      { name: "Mitchell Starc", photo: "/kkr.png" },
      { name: "Angkrish Raghuvanshi", photo: "/kkr.png" },
      { name: "Ramandeep Singh", photo: "/kkr.png" },
      { name: "Sherfane Rutherford", photo: "/kkr.png" },
      { name: "Manish Pandey", photo: "/kkr.png" },
      { name: "Mujeeb Rahman", photo: "/kkr.png" },
      { name: "Gus Atkinson", photo: "/kkr.png" },
    ],
    logo: "",
  },
  LSG: {
    teamPlayers: [
      { name: "KL Rahul (c)", photo: "/lsg.png" },
      { name: "Quinton de Kock", photo: "/lsg.png" },
      { name: "Nicholas Pooran", photo: "/lsg.png" },
      { name: "Ayush Badoni", photo: "/lsg.png" },
      { name: "Kyle Mayers", photo: "/lsg.png" },
      { name: "Marcus Stoinis", photo: "/lsg.png" },
      { name: "Deepak Hooda", photo: "/lsg.png" },
      { name: "Ravi Bishnoi", photo: "/lsg.png" },
      { name: "Naveen-ul-Haq", photo: "/lsg.png" },
      { name: "Krunal Pandya", photo: "/lsg.png" },
      { name: "Yudhvir Singh", photo: "/lsg.png" },
      { name: "Prerak Mankad", photo: "/lsg.png" },
      { name: "Yash Thakur", photo: "/lsg.png" },
      { name: "Amit Mishra", photo: "/lsg.png" },
      { name: "Mark Wood", photo: "/lsg.png" },
      { name: "Mayank Yadav", photo: "/lsg.png" },
      { name: "Mohsin Khan", photo: "/lsg.png" },
      { name: "Devdutt Padukone (Traded)", photo: "/lsg.png" },
      { name: "Shivam Mavi", photo: "/lsg.png" },
      { name: "Arshin Kulkarni", photo: "/lsg.png" },
      { name: "M Siddharth", photo: "/lsg.png" },
      { name: "Ashton Turner", photo: "/lsg.png" },
      { name: "David Willey", photo: "/lsg.png" },
    ],
    logo: "",
  },
  PKXII: {
    teamPlayers: [
      { name: "Shikhar Dhawan (c)", photo: "/pxii.png" },
      { name: "Matthew Short", photo: "/pxii.png" },
      { name: "Prabhsimran Singh (wk)", photo: "/pxii.png" },
      { name: "Jitesh Sharma (wk)", photo: "/pxii.png" },
      { name: "Sikandar Raza", photo: "/pxii.png" },
      { name: "Rishi Dhawan", photo: "/pxii.png" },
      { name: "Liam Livingstone", photo: "/pxii.png" },
      { name: "Atharva Taide", photo: "/pxii.png" },
      { name: "Arshdeep Singh", photo: "/pxii.png" },
      { name: "Nathan Ellis", photo: "/pxii.png" },
      { name: "Sam Curran", photo: "/pxii.png" },
      { name: "Kagiso Rabada", photo: "/pxii.png" },
      { name: "Harpreet Brar", photo: "/pxii.png" },
      { name: "Rahul Chahar", photo: "/pxii.png" },
      { name: "Harpreet Bhatia", photo: "/pxii.png" },
      { name: "Vidwath Kaverappa", photo: "/pxii.png" },
      { name: "Shivam Singh", photo: "/pxii.png" },
      { name: "Harshal Patel", photo: "/pxii.png" },
      { name: "Chris Woakes", photo: "/pxii.png" },
      { name: "Ashutosh Sharma", photo: "/pxii.png" },
      { name: "Vishwanath Pratap Singh", photo: "/pxii.png" },
      { name: "Shashank Singh", photo: "/pxii.png" },
      { name: "Tanay Thyagarajann", photo: "/pxii.png" },
      { name: "Prince Choudhary", photo: "/pxii.png" },
      { name: "Rilee Rossouw", photo: "/pxii.png" },
    ],
    logo: "",
  },
  RCB: {
    teamPlayers: [
      { name: "Faf du Plessis (c)", photo: "/rcb.jpeg" },
      { name: "Glenn Maxwell", photo: "/rcb.jpeg" },
      { name: "Virat Kohli", photo: "/rcb.jpeg" },
      { name: "Rajat Patidar", photo: "/rcb.jpeg" },
      { name: "Anuj Rawat", photo: "/rcb.jpeg" },
      { name: "Dinesh Karthik", photo: "/rcb.jpeg" },
      { name: "Suyash Prabhudessai", photo: "/rcb.jpeg" },
      { name: "Will Jacks", photo: "/rcb.jpeg" },
      { name: "Mahipal Lomror", photo: "/rcb.jpeg" },
      { name: "Karn Sharma", photo: "/rcb.jpeg" },
      { name: "Manoj Bhandage", photo: "/rcb.jpeg" },
      { name: "Mayank Dagar (Traded)", photo: "/rcb.jpeg" },
      { name: "Vyshak Vijay Kumar", photo: "/rcb.jpeg" },
      { name: "Akash Deep", photo: "/rcb.jpeg" },
      { name: "Mohammed Siraj", photo: "/rcb.jpeg" },
      { name: "Reece Topley", photo: "/rcb.jpeg" },
      { name: "Himanshu Sharma", photo: "/rcb.jpeg" },
      { name: "Rajan Kumar", photo: "/rcb.jpeg" },
      { name: "Cameron Green (Traded)", photo: "/rcb.jpeg" },
      { name: "Alzarri Joseph", photo: "/rcb.jpeg" },
      { name: "Yash Dayal", photo: "/rcb.jpeg" },
      { name: "Tom Curran", photo: "/rcb.jpeg" },
      { name: "Lockie Ferguson", photo: "/rcb.jpeg" },
      { name: "Swapnil Singh", photo: "/rcb.jpeg" },
    ],
    logo: "",
  },
  RR: {
    teamPlayers: [
      { name: "Sanju Samson (c) (wk)", photo: "/rr.png" },
      { name: "Jos Buttler", photo: "/rr.png" },
      { name: "Shimron Hetmyer", photo: "/rr.png" },
      { name: "Yashasvi Jaiswal", photo: "/rr.png" },
      { name: "Dhruv Jurel", photo: "/rr.png" },
      { name: "Riyan Parag", photo: "/rr.png" },
      { name: "Donovan Ferreira", photo: "/rr.png" },
      { name: "Kunal Rathore", photo: "/rr.png" },
      { name: "Ravichandran Ashwin", photo: "/rr.png" },
      { name: "Kuldeep Sen", photo: "/rr.png" },
      { name: "Navdeep Saini", photo: "/rr.png" },
      { name: "Prasidh Krishna", photo: "/rr.png" },
      { name: "Sandeep Sharma", photo: "/rr.png" },
      { name: "Trent Boult", photo: "/rr.png" },
      { name: "Yuzvendra Chahal", photo: "/rr.png" },
      { name: "Adam Zampa", photo: "/rr.png" },
      { name: "Avesh Khan (Traded)", photo: "/rr.png" },
      { name: "Rovman Powell", photo: "/rr.png" },
      { name: "Shubham Dubey", photo: "/rr.png" },
      { name: "Tom Kohler-Cadmore", photo: "/rr.png" },
      { name: "Abid Mushtaq", photo: "/rr.png" },
    ],
    logo: "",
  },
};
